### ISSUE TITLE
is there any way to toggle the visibility of the redux-logger logs in the browser console?

### ISSUE THREAD

**Issue by benmonro** [evgenyrodionov/redux-logger#220]
there's times when i'm in the browser console when I'd just like to toggle the visibility of the redux-logger messages in console... is there anyway to do this?

**Comment by evgenyrodionov** [comment]
Nope

**Comment by benmonro** [comment]
would it be hard to implement something like that?  there's times when I wish I could hide them so I can see other console logs...

**Comment by evgenyrodionov** [comment]
Use `collapsed` option, it's better for readability

**Comment by benmonro** [comment]
Yeah... I do. Still would be nice to have a way to hide them somehow

**Comment by evgenyrodionov** [comment]
I do not see the need for another setting, and you always can clear console using browser's feature.

**Comment by Gurpret7** [comment]
Would love to have a way to mute them sometimes.

**Comment by mkonikov** [comment]
Same.

Especially when working across different teams managing different properties of a webpage. When one team enables for their components it clogs the entire console. Wish there was a way to hide.

**Comment by eranimo** [comment]
I would recommend not initializing redux-logger if a certain local storage value is found.

**Comment by vincerubinetti** [comment]
I find I need to toggle collapsed on/off very frequently, sometimes even within the same testing/build session. Maybe one solution would be if the `collapsed` option could accept a function instead of a boolean, so you could do something like this:

```javascript
const logger = createLogger({
  collapsed: () => window.collapsed === 'boolean' ? window.collapsed : true
});
```

Then in the console, you could set `collapsed=false` and all future actions would be logged open.

Of course, this probably should really be a feature of the browser. Browsers should have a keyboard shortcut to auto-collapse or auto-expand all console messages.
