### ISSUE TITLE
Not seeing Redux-Thunk Actions in Log

### ISSUE THREAD

**Issue by foxmicha** [evgenyrodionov/redux-logger#271]
After following the readme's suggestion of placing the redux-logger as the last middleware I am still not seeing any redux-thunks pushed out to the console log. Will the redux-logger not grab redux-thunks because they don't have an action type?

**Comment by evgenyrodionov** [comment]
Please, can you reproduce problem at codesandbox.io?

**Comment by foxmicha** [comment]
My application is a React-Native application but I'll try to take a sample of it and convert it to pure React.

**Comment by foxmicha** [comment]
Here's a small sample: https://codesandbox.io/s/y3l37rvwxx

What I would expect to see is an action of "trackScreenTime" before the "setTrackedScreen" action but that thunk never seems to show.

**Comment by tswaters** [comment]
Looks like this is working as expected.    If you wanted to see `thunk` actions, change the order of the middleware application.   redux-thunk checks if an action is a function and is calls it, passing `dispatch` and `getState`.... otherwise it calls dispatch on the action normally.  So, a thunk action is only a function.   

If the logger got a thunk, it wouldn't have anything to show about it (it logs the action name as `undefined`), and it won't call back into redux itself to apply changes to the store via reducers (so prev/next state will be the same) - it let's the function do that.

This is why typically logger goes last -- so you can see the relevant dispatches the thunk performs, not the thunk itself.

**Comment by grushetsky** [comment]
@tswaters, absolutely!

@foxmicha, `redux-logger` is supposed to work with plain action objects and not functions. Why would you want to log a thunk action?
